### ISSUE TITLE
NuGet Dependency on OctoPack

### ISSUE THREAD

**Issue by kimpenhaus** [marcio-azevedo/serilog-sinks-slack#7]
Hi Marcio,

I've recently installed the beta version of your Serilog.Sinks.Slack and was wondering why there is a dependency on `OctoPack 3.5.2` when I do install the NuGet package.

As far as I can see, this is just for internal purpose during build / deployment.
Is it possible for you to drop this dependency during NuGet package generation?

Thanks and cheers,
Marcus

**Comment by marcio-azevedo** [comment]
Hi Marcus,

You're right, it shouldn't since the [Serilog.Sinks.Slack.nuspec](https://github.com/marcio-azevedo/serilog-sinks-slack/blob/master/src/Serilog.Sinks.Slack/Serilog.Sinks.Slack.nuspec) doesn't reference that package as dependency.
Probably something related with the CI process. I'll check and try to fix it. Thanks for your input.

Regards,
Márcio

**Comment by marcio-azevedo** [comment]
Ok, it's fixed, I'll close this issue.

Thanks for the feedback.

**Comment by kimpenhaus** [comment]
awesome - thanks!
